version: "3.9"

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    command: uvicorn --factory src.app.main:create_app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
