"""Create batches table

Revision ID: 63e5f2295d5c
Revises: 
Create Date: 2025-05-26 11:58:05.022419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e5f2295d5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('shift_task_name', sa.String(), nullable=False),
    sa.Column('work_center', sa.String(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('brigade', sa.String(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('nomenclature', sa.String(), nullable=False),
    sa.Column('ekn_code', sa.String(), nullable=False),
    sa.Column('rc_identifier', sa.String(), nullable=False),
    sa.Column('shift_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('shift_end_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('product_items',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('batch_oid', sa.UUID(), nullable=False),
    sa.Column('unique_code', sa.String(), nullable=False),
    sa.Column('is_aggregated', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_oid'], ['batches.oid'], ),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('unique_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_items')
    op.drop_table('batches')
    # ### end Alembic commands ###
